python run_summarization.py \
    --model_name_or_path ./tmp/Soccer/bart/tst-summarization/checkpoint-2800 \
    --do_predict \
    --test_file ./data/topic_shift_sampled/test/Family_test_sampled.json \
    --text_column document \
    --summary_column summary \
    --source_prefix "summarize: " \
    --output_dir ./crossdomain/Soccer2Familt-summarization \
    --per_device_eval_batch_size=36 \
    --num_beams=4 \
    --fp16 \
    --predict_with_generate
