python run_summarization.py \
    --model_name_or_path google/pegasus-x-base \
    --tokenizer_name google/pegasus-x-large \
    --do_train \
    --do_eval \
    --do_predict \
    --train_file ./data/genre_shift_sampled/train/cnndm_train_sampled.json \
    --validation_file ./data/genre_shift_sampled/valid/cnndm_valid_sampled.json \
    --test_file ./data/genre_shift_sampled/test/cnndm_test_sampled.json \
    --text_column document \
    --summary_column summary \
    --source_prefix "summarize: " \
    --num_train_epochs=1 \
    --eval_strategy steps \
    --eval_steps 200 \
    --save_strategy steps \
    --save_steps 200 \
    --output_dir ./tmp/cnndm/pegasus-x/tst-summarization \
    --per_device_train_batch_size 12 \
    --per_device_eval_batch_size 24 \
    --fp16 \
    --num_beams 8 \
    --overwrite_output_dir \
    --load_best_model_at_end \
    --metric_for_best_model loss \
    --greater_is_better false \
    --predict_with_generate
